---

- name: perform installation
  include_tasks: install/{{ ansible_os_family }}.yml

- name: define distribution-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: setup_user.yml
- include_tasks: install_sentry_cli.yml
  when: sodar_core_app_sentry_enable_releases
- include_tasks: setup_systemd.yml
- include_tasks: install_app.yml
